import("//testing/test.gni")

source_set("privacy") {
  sources = [
    "privy_privacy_service.cc",
    "privy_privacy_service.h",
    "privy_privacy_service_factory.cc",
    "privy_privacy_service_factory.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//components/privy_privacy:core",
    "//content/public/browser",
  ]
}

test("privy_privacy_service_unittests") {
  sources = [ "privy_privacy_service_unittest.cc" ]

  deps = [
    ":privacy",
    "//base/test:run_all_unittests",
    "//base/test:test_support",
    "//components/privy_privacy:core",
    "//testing/gtest",
    "//url",
  ]
}
